### ISSUE TITLE
update flutter sdk

### ISSUE THREAD

**Issue by xiaomsh** [payu-intrepos/PayUCustomBrowser-Flutter#2]
The current Dart SDK version is 3.4.3.

Because wallet depends on payubiz_cb_flutter >=0.0.2-dev.1 which requires SDK version >=2.18.5 <=3.3.4, version solving failed.

please update the flutter sdk to the latest

**Comment by shahfaizalc** [comment]
we are releasing the latest version soon. will update you on this

**Comment by xiaomsh** [comment]
very good

**Comment by xiaomsh** [comment]
@shahfaizalc 

any update?

if you are facing some problems, you can publish a pre version, which only need change one line code as below

```
sdk: '>=3.0.0 <4.0.0'
```

**Comment by xiaomsh** [comment]
when I update the flutter sdk to 3.24.0, the error happened

The current Dart SDK version is 3.5.0.
Because demo depends on payubiz_cb_flutter >=0.0.2-dev.1 which requires SDK version >=2.18.5 <=3.4.4, version solving failed.

Please Please Please use the official plugin sdk limit

`
sdk: '>=(what you need the min version) <4.0.0'
`

If you set the max version as a lower version , you need update this library when flutter sdk update, this is waste more time. you can see when you create a flutter plugin, the pubspec.yaml set the max version to 4.0.0, why not use this?


I really really really want your team to update this, thanks

**Comment by xiaomsh** [comment]
tell the details, the latest plugin I use which cause this problem is below

payubiz_cb_flutter: ^0.0.3

**Comment by vipinRohilla** [comment]
Hi Team,
we are getting this error

android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:271: error: cannot find symbol
flutterEngine.getPlugins().add(new com.payu.payubiz_cb_flutter.PayuCustomBrowserFlutterPlugin());

any resolution?
@wenchaosong 
@shahfaizalc

**Comment by shahfaizalc** [comment]
@wenchaosong @wenchaosong @vipinRohilla please update to our latest version 0.0.3 we have updated to the dart version

**Comment by vipinRohilla** [comment]
> @wenchaosong @wenchaosong @vipinRohilla please update to our latest version 0.0.3 we have updated to the dart version

Thank you @shahfaizalc

**Comment by xiaomsh** [comment]
@shahfaizalc  I think you didn't understand what I mean

I updated the flutter sdk to 3.24.0 today morning, the dart sdk is 3.5.0

but this plugin latest version 0.0.3 is not supported, it is support 3.4.4 , which flutter sdk version is 3.22.3


so I suggest your team to update the pubspec.yaml set the max version to 4.0.0

**Comment by shahfaizalc** [comment]
we understand, our current SDK support  3.4.4. kindly use the same. 
We have planned release in coming week, we will set the max version on that release. sorry for the inconvenience.

**Comment by xiaomsh** [comment]
very glad to hear this, come on , I can't wait any more

**Comment by shahfaizalc** [comment]
https://pub.dev/packages/payubiz_cb_flutter @wenchaosong pls check this

**Comment by xiaomsh** [comment]
It is ok now
